import Head from "next/head";
import {
  AiFillFacebook,
  AiFillGithub,
  AiFillInstagram,
  AiFillLinkedin,
  AiFillTwitterCircle,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import kelsiehamptonimg from "../public/kelsiehamptonimg.png";
import checkicon from "../public/checkicon.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kelsie Hampton</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-robotobold text-xl">
              Developed By: Ron The Web Dev
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Kelsie Hampton
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Freelance Web Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Laudantium fugit ipsam unde. Repellendus delectus distinctio dicta
              dolore omnis cupiditate ea veritatis, aspernatur, voluptatum neque
              perspiciatis aut explicabo maxime ullam iusto.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillFacebook className="cursor-pointer" />
              <AiFillGithub className="cursor-pointer" />
              <AiFillInstagram className="cursor-pointer" />
              <AiFillLinkedin className="cursor-pointer" />
              <AiFillTwitterCircle className="cursor-pointer" />
              <AiFillMail className="cursor-pointer" />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-120 md:w-120">
              <Image
                src={kelsiehamptonimg}
                layout="fill"
                objectFit="cover"
                alt=""
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white uppercase">
              About Me
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 mb-10">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
              omnis pariatur porro totam magnam alias natus ullam culpa
              excepturi dignissimos iusto maxime eveniet ex hic voluptate odit
              dolorem aut, sint nisi! Eos, ducimus? Voluptas, recusandae.
              Distinctio optio ab voluptas ut quas corrupti soluta natus nostrum
              atque laborum! Sunt ipsam placeat rerum consectetur ratione,
              veniam voluptates itaque velit praesentium, ab labore natus
              doloribus sit officiis ea deserunt laudantium eos eaque nostrum
              laborum, vel iusto assumenda distinctio soluta. Fugiat ab
              accusantium fuga!
            </p>
          </div>
          <div>
            <h3 className="text-3xl py-1 dark:text-white uppercase">
              Services
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
              omnis pariatur porro totam magnam alias natus ullam culpa
              excepturi dignissimos iusto maxime eveniet ex hic voluptate odit
              dolorem aut, sint nisi! Eos, ducimus? Voluptas, recusandae.
              Distinctio optio ab voluptas ut quas corrupti soluta natus nostrum
              atque laborum! Sunt ipsam placeat rerum consectetur ratione,
              veniam voluptates itaque velit praesentium, ab labore natus
              doloribus sit officiis ea deserunt laudantium eos eaque nostrum
              laborum, vel iusto assumenda distinctio soluta. Fugiat ab
              accusantium fuga!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={checkicon} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Custom Designs</h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Doloribus nostrum illo blanditiis iure placeat autem asperiores
                neque, ipsa harum cumque. Dolor a, assumenda voluptatum sit rem
                ullam tempore eos voluptates maiores, cumque laboriosam
                accusamus debitis, distinctio minima nihil in voluptatibus.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={checkicon} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Custom Wireframes
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Necessitatibus commodi magni asperiores consequatur
                exercitationem dolores quas perferendis quo ducimus nemo, animi
                placeat sed eveniet. Blanditiis sunt illum ab, dolor autem vero
                adipisci! Laboriosam accusantium cum maiores, omnis dignissimos
                saepe aperiam.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={checkicon} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Logos & Graphics
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae
                at totam doloribus maiores architecto! Possimus laudantium in
                quisquam magnam delectus, dignissimos culpa! Architecto sequi
                deserunt odio exercitationem consequatur est iste obcaecati
                alias voluptatem, id repellendus repudiandae, quod aspernatur
                iure harum?
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white uppercase">
              Portofolio
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Voluptatum nulla numquam libero commodi nostrum deleniti itaque
              non impedit earum. Ullam laudantium provident laborum? Similique,
              porro. Nam vero eveniet, mollitia necessitatibus enim tempora.
              Ipsa, dolor quisquam! Dolores modi laboriosam laborum omnis optio
              facilis vitae harum autem est delectus? Mollitia debitis qui iusto
              voluptatibus quaerat culpa, nobis beatae consequuntur quis
              incidunt! Ullam dolores aperiam perferendis architecto nobis,
              laudantium eveniet sunt quo perspiciatis quas atque ea repellat
              dolor vel optio facilis! Sequi, obcaecati.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt=""
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
